### ISSUE TITLE
Problem: ZMTP Protocol is not complete

### ISSUE THREAD

**Issue by somdoron** [zeromq/gogozmq#10]
The ZMTP protocol is not yet complete, the greeting still missing the mechanism, as server, filler and the ready command.

As we only implement the NULL mechanism I would suggest to start with ZMTP v2.0 which is easier to implement.

What do you think?

**Comment by taotetek** [comment]
@somdoron So far, we do not care about ZMTP v2.0 compatbility.  My preference would be for getting the ZMTP 3.0 handshake working, but only allowing NULL mechanism for now.

ZMTP 3.0 with support for PUSH / PULL, CLIENT / SERVER, and PUB / SUB and NULL security would get us to the point that we could start using gogozmq in earnest for some things.

**Comment by somdoron** [comment]
OK, just ZMTP v3.0 is more complicated to implement. Anyway I will complete the NULL mechanism, as I cannot test the message sending without that.

**Comment by hintjens** [comment]
You can start with 1.0 and add the rest later, if you want a minimal place
to start.

**Comment by taotetek** [comment]
@hintjens @somdoron would that make it simpler to iterate?  if starting with an earlier version and iterating one problem at a time to 3.0 is helpful, I'm all for it.

**Comment by hintjens** [comment]
Yes, its a natural and easy progression.

**Comment by taotetek** [comment]
:thumbsup: in that case
